// patchNotes.ts: player-facing release marker + patch-note history.
//
// Extracted out of App.svelte (2026-07-15) so BOTH the in-game About/Patch
// Notes tabs AND the public Landing page (src/Landing.svelte) read from a
// single source of truth. Adding a release here now updates the game's Patch
// Notes tab and the landing page's news strip in one edit.
//
// APP_VERSION is a human-readable release marker, bumped by hand whenever
// there's a user-visible batch of changes worth calling out. It is DISTINCT
// from SAVE_VERSION (save.ts), which is the save SCHEMA version, bumped only
// when the save shape changes. Newest PATCH_NOTES entry first.
//
// Reset to a disciplined X.Y.Z scheme starting 2026-07-07 (Y bumps per feature
// release, Z bumps per minor fix). The pre-reset 0.6.0-0.9.0 history below is
// left untouched (never rewrite patch-note history), so this deliberately reads
// as "0.2.0 newer than 0.9.0" once, only here.

export const APP_VERSION = "0.12.1";

export const PATCH_NOTES: { version: string; summary: string }[] = [
  { version: "0.12.1", summary: "Fleet Admiral leveling rebalanced. Early levels now come at a sensible pace instead of taking days, and your finite work finally counts: facility upgrades, crafting, research, and ship-building all grant meaningful Fleet Admiral experience now, on top of the steady trickle from missions. This is a temporary tuning pass ahead of the full balance, so exact numbers will keep moving. Your save carries over untouched and simply levels up faster from here." },
  { version: "0.12.0", summary: "Console: a ground-up interface redesign that makes the growing game far easier to read and move through (no new gameplay, your save and the economy are untouched). Navigation is now FIVE clear perspectives, each its own console screen you drive with buttons instead of deep nested tabs: HOME (game overview, the Help manual, and a Statistics page tracking your lifetime totals and fleet), PERSONNEL (your Fleet Admiral and your Captains, with talent trees, ship assignment, and equipment, everything about a person on one page), FACILITIES (every building you manage, Refinery, Fabricator, Research Lab, Fuel Depot, Shipyard, Warehouse, and the Salvage Bay, shown on a dashboard and each opening its own console to produce and upgrade), LOGISTICS (everything you own, Ships, Ship Equipment, Crew Equipment, and Materials), and OPERATIONS (missions you send captains on, Gathering now with Combat, Exploration, and Battlespace reserved for later). The old left-hand rails and buried sub-tabs are gone: each screen lands on an overview, and pages swap in place. Settings now open from your admiral portrait at the top (Profile, Options, Community with a Discord link, Patch Notes, and more). Highlights: your captain and Fleet Admiral talent trees open in focused windows; the ship view keeps the familiar paper-doll for installing systems; salvaged materials now sit right alongside your other materials; every mission has a View Info panel with the full drop table plus a held / cap readout on each drop icon; storage and salvage moved to their own building consoles; and buttons now follow your chosen theme. It is the same game, laid out the way it always should have been." },
  { version: "0.11.1", summary: "Fleet Management: two ways to manage a growing fleet. EXPAND DOCKS: your docks start capped at 8 hulls; a new timed Expand Docks upgrade raises that cap by one ship at a time. SHIP SALVAGE: break down a ship you no longer need. Its installed systems return to your spare pool first, so you never lose crafted gear, you recover a share of the materials and credits that built the hull, and the docks slot frees up immediately. A ship out on an active mission cannot be scrapped, and salvaging asks for confirmation first. (Ship teardown is instant for now; it becomes a proper timed process later, since tearing a whole hull apart should not be free.)" },
  { version: "0.11.0", summary: "Ship Systems: the first equipment update. Every ship now has four equipment slots (Cargo Bay, FTL Drive, Reactor Core, and a Spec Utility slot for your hull's specialization) and comes pre-fitted with a Standard-Issue baseline in each, so a bare ship is always ready to fly. Research SHIP-SYSTEM BLUEPRINTS at the Research Lab, then craft them at the Fabricator from your refined materials and components. Crafted systems are real upgrades over the baseline: each carries a quality grade (0 to 5), a rarity, and an item level that together set how much it boosts your ship. New SHIP SYSTEMS screen, opened from the Docks or a captain's overview: a paper-doll of the hull with every slot, install or uninstall in one tap, watch the ship's stats move as you fit gear, and each fitted slot shows exactly what its system grants. A live slot is never left empty: uninstall and the baseline drops back into place. SEE YOUR SYSTEMS: a new Ship Systems tab in the Warehouse lays out every system you own, grouped by slot, each tile showing its icon, item level, and rarity, with a full detail tooltip. Your spare systems have a storage cap you can raise with a timed Systems Bay upgrade. SALVAGE: break down a spare system you no longer need to recover a share of the materials that built it, so a full bay never blocks you. The rare Damaged Reactor Housing from the Salvage mission can be broken down for a tiered roll at rarer materials, with the ceiling rising as your Fleet Admiral levels and a new Salvage Operations talent improving the odds; a new Salvaged Materials tab in the Warehouse holds them. Plus cleanup and legibility: proper names throughout (the old placeholder Refined Material is now Titanium Ingot and a dead Components entry is gone), and your crafting skill levels up as you fabricate. Everything migrates automatically, so existing ships arrive fully fitted. (Weapons, shields, and the combat systems these slots are built toward arrive with combat; a dedicated equipment and consumables storage facility, a Help tab, and a wider set of material recipes come in the next UI update; baseline-gear stat tuning follows at balancing.)" },
  { version: "0.10.2", summary: "A small polish and safety patch. The ambient starfield and the activity log now recolor with your chosen theme, so switching themes looks complete instead of leaving a few stray colors behind. Save safety: if a save ever fails to load, the game no longer silently starts over. It shows you the raw save text so you can copy a backup first, keeps the old save untouched, and only starts fresh when you explicitly choose to. Accessibility: every popup now keeps keyboard focus inside it, closes on Escape (except the save-recovery one, which needs a real choice), and is labeled for screen readers. Plus some behind-the-scenes cleanup of unused styles." },
  { version: "0.10.1", summary: "The game now notices when a new version has been deployed and shows a slim \"a new version is available\" banner at the top so you can refresh to pick up the latest fixes. No more sitting on a stale build without knowing. The banner has a one-click Export Save to grab a backup before you reload (it stays open so you don't lose your place), a Refresh button, and a dismiss that just snoozes: if you're not ready, it quietly steps aside and reminds you again a few hours later. No forced reloads, and your progress auto-saves either way. It matches your chosen theme, frosted glass and all." },
  { version: "0.10.0", summary: "The big production-economy and shipbuilding update: the full chain from research to a ship built from scratch. RESEARCH LAB: research blueprints (time plus credits) that permanently unlock what you can build, in tiers gated by the lab's level. FABRICATOR: craft those blueprints into real components from your materials. The Refinery and Fabricator now run as per-slot PRODUCTION LINES you configure independently: pick a tier, an item, and an amount, so every slot can run a different recipe at once. Starting a craft RESERVES its materials up front, so concurrent lines never double-spend the same stockpile: any item's tooltip now breaks its count into Allocated (held by running crafts), Free (available to start something new), and Total. Cancel a line and the unstarted materials refund to your Free pool (only the iteration already in progress is spent), and an amount can't exceed what you can currently reserve, so there's no stuck state. Reserved materials are protected from EVERY spender now, so founding or upgrading a facility (or a ship build) can't quietly eat the parts a running line set aside. The Refinery makes the specific materials the Fabricator needs (Titanium Ore into Titanium Ingots, Polysilicate Ore into Polysilicate Wafers), so mining, refining, and fabricating is playable end to end. SHIPYARD (Fleet Sector): found it once (credits plus Fleet-Admiral level), then BUILD ships from your fabricated components and credits over a timed construction; the finished hull parks in your fleet, ready to assign to a captain at the Docks, closing the loop. The old instant credit-buy (Requisition) is retired: ships come out of the pipeline now. Plus quality-of-life throughout: themes recolor the whole interface, fuel readouts are honest with a self-sustaining fuel-runway estimate, and every research, craft, and build timer reads as real time (about 2h 15m) with a progress bar. (Refits, repairs, advanced research-gated hulls, and drones for parallel building all come later.)" },
  { version: "0.9.0", summary: "Five missions available from the start: a free Local Deuterium Skim that gathers fuel-grade Deuterium Ice at no fuel cost, plus Local Asteroid, Lunar Mine Contract, Salvage Skirmish Wreckage, and Forage Minerals & Flora, the four resource runs each hauling back its own trio of raw materials (12 in total to feed future crafting). Salvage and Forage ask for a slightly more experienced captain before they'll launch. New Mission Control facility tracks your available missions and their completion counts; more missions will unlock here as new content arrives. Missions now burn fuel for the round trip, and fuel runs on a proper economy: the new Fuel Depot automatically refines Deuterium Ice into fuel through processing pipelines you can expand (upgrade for more pipelines, more fuel per batch, and less ice per batch). Run the free fuel skim, refine the ice, and you stay self-sufficient. If a captain is short at launch, the shortfall is auto-bought with credits as a pricey backup (costing a short refuel delay on that trip), and only stops repeating if you're also out of credits. A fuel gauge in the top bar shows at a glance whether you're producing more fuel than you're burning. Each ship has its own fuel capacity (how far it can range) and engine efficiency (how little it burns). Every mission now shows its XP earned per tick and its dispatch requirements up front (captain level, cargo space, fuel), with a clear reason spelled out when you can't launch. Also: warehouse fill-tiles are smaller on desktop, and their tooltips now open on a single tap on mobile." },
  { version: "0.8.0", summary: "New Warehouse facility: your materials now have real storage, split into Raw / Refined / Component tabs (plus placeholder tabs for what's coming), each with a fill-tile gauge showing how full it is, and timed capacity upgrades that double how much you can hold. Storage now has caps, so producers automatically pause when a material is full instead of wasting it. Refining got a proper order system: queue a fixed batch (Refine N) or run it continuously, watch live status and why it paused (out of ingredients, or storage full), stop an order any time, with an optional confirmation prompt you can toggle in the System tab's Options. Offline progress now advances your facilities while you're away, capped at 2 days. Groundwork for a bigger crafting economy: the base ores are renamed to Titanium / Polysilicate / Iridium Ore, with placeholder raw, refined, and component items seeded for future recipes." },
  { version: "0.7.0", summary: "Navigation reorganized: Homeworld and Sector Space are now unified under a new Locations tab (each place keeps its own sub-tabs), and Facilities are grouped by owner (Homeworld, Fleet Sector, Ships). Same content, tidier layout, fewer tabs." },
  { version: "0.6.0", summary: "New Facilities tab: you can now build and upgrade a Refinery, then run refine jobs that turn common ore into refined material over time, and each upgrade unlocks another refine slot so several jobs run at once, with the later upgrades gated behind your Fleet Admiral level and Homeworld talents. Behind the scenes, all your materials moved into a single unified inventory, and existing saves migrate automatically." },
  { version: "0.5.0", summary: "Captains and your Fleet Admiral now earn XP every tick while missions run, instead of only when a mission cycle finishes, so leveling feels steady and continuous, and the Fleet Admiral now climbs much faster the more captains you have out on missions at once. Unlocking captain slots 3 and 4 now also requires reaching a Fleet Admiral level (on top of the existing talent cost), and captain slots you can actually work toward now read \"Locked\" instead of \"Coming Soon.\"" },
  { version: "0.4.0", summary: "Ships are now real, swappable hulls with distinct stats: cargo capacity, transit speed, and extraction yield all change how a captain's missions play out. New Sector Space > Starbase area to manage your fleet, assign hulls to captains, and buy new hulls with credits. Existing saves auto-upgrade, giving every captain a starter Freighter." },
  { version: "0.3.0", summary: "Talent trees are now an explorable radial \"skill web\" you pan around, revealing new nodes as you learn. Captains pick a specialization (Prospector, Tactician, or Explorer), and Fleet Admiral talents are organized into 5 navigable categories. Learned nodes power up glowing links between them. Existing saves are migrated automatically." },
  { version: "0.2.0", summary: "Reworked mission loot so uncommon and rare materials can both drop in the same tick instead of one replacing the others; talent bonuses now target a specific material tier each. Added Import Save. Version numbering restarts here: 0.2.1/0.2.2 for small fixes, 0.3.0 for the next feature." },
  { version: "0.9.0", summary: "Widened the app to use most of the screen instead of a narrow centered column; retired the diagonal-corner panel look for a flatter style; moved the app's branding into this About tab." },
  { version: "0.8.0", summary: "Reworked scrolling so only the active tab's content scrolls, not the whole page; added \"Coming Soon\" locked placeholders for future sub-tabs and captain slots." },
  { version: "0.7.0", summary: "Rebuilt navigation: a global header with Fleet Admiral level/XP and a single fleet-wide tick, a dedicated Fleet Captain's tab, and a mission-first Fleet Operations tab." },
  { version: "0.6.0", summary: "Added Captain Talents and Homeworld Talents: two talent trees plus Fleet Admiral leveling." },
];
