// patchNotes.ts -- Player-facing release marker + patch-note history.
//
// Extracted out of App.svelte (2026-07-15) so BOTH the in-game About/Patch
// Notes tabs AND the public Landing page (src/Landing.svelte) read from a
// single source of truth. Adding a release here now updates the game's Patch
// Notes tab and the landing page's news strip in one edit.
//
// APP_VERSION is a human-readable release marker, bumped by hand whenever
// there's a user-visible batch of changes worth calling out. It is DISTINCT
// from SAVE_VERSION (save.ts) -- that's the save SCHEMA version, bumped only
// when the save shape changes. Newest PATCH_NOTES entry first.
//
// Reset to a disciplined X.Y.Z scheme starting 2026-07-07 (Y bumps per feature
// release, Z bumps per minor fix) -- the pre-reset 0.6.0-0.9.0 history below is
// left untouched (never rewrite patch-note history), so this deliberately reads
// as "0.2.0 newer than 0.9.0" once, only here.

export const APP_VERSION = "0.12.0";

export const PATCH_NOTES: { version: string; summary: string }[] = [
  { version: "0.12.0", summary: "The Refinery and Fabricator are reworked into per-slot production lines: each craft slot is now configured independently -- pick a tier, then an item, then an amount -- so every slot can run a different recipe at the same time, instead of one order shared across all slots. Starting a craft RESERVES its materials up front, so several lines running at once can never double-spend the same stockpile -- you can see exactly what's held back on any item's tooltip, which now breaks its count into Allocated (reserved by running crafts), Free (available to start something new), and Total (what you physically have). Changed your mind on a line? Cancel it and the unstarted materials are refunded straight back to your Free pool -- only the one iteration already in progress is spent. And because a line's amount is capped at what you can currently reserve, there's no way to over-commit yourself into a stuck state. The Refinery also learned to make the specific materials the Fabricator actually needs -- Titanium Ore now refines into Titanium Ingots and Polysilicate Ore into Polysilicate Wafers -- so the full chain from mining to refining to fabricating components is playable end to end for the first time. Note that fabricated components still aren't consumed by anything just yet -- they'll become usable with the Shipyard, the next feature, where you'll build ships from the parts you've made." },
  { version: "0.11.0", summary: "New Fabricator facility: you can now craft the blueprints you've researched into real components, spending your stockpiled materials to build them. Each blueprint runs as a craft order -- pick a fixed batch (Craft N) or run it continuously across your craft slots, exactly like the Refinery's refine orders. Orders that run out of materials pause on their own and auto-resume the moment you have enough again, so you can queue up a long run and walk away. Upgrading the Fabricator unlocks higher component tiers so you can build more advanced designs, and adds more craft slots so several crafts progress at once. Blueprints organize into tiers -- and because the more advanced components are built from the simpler ones, you'll craft the basic pieces first and assemble them into the bigger parts. Note that fabricated components aren't consumed by anything just yet -- they'll become usable with the Shipyard, the next feature, where you'll build ships from the components you've made; for now, the Fabricator is how you stock up the parts that are coming. Also a tidy-up pass: the old Homeworld instant-craft panel and the placeholder Home Planet resource list have been retired -- the Warehouse and the new facility panels replace them, so crafting now lives entirely in the timed facilities instead of an instant-click sub-tab." },
  { version: "0.10.0", summary: "New Research Lab facility: you can now research blueprints -- each one costs research time plus credits and, once complete, permanently unlocks something you'll be able to build. Blueprints are organized into tiers, and higher tiers become available as you upgrade the lab, so more advanced designs open up the more you invest in research. Upgrading the lab also gives you more research slots, letting several blueprints progress at once. Research runs on the same game-time clock as everything else, so projects keep advancing through offline time. Note that researching a blueprint doesn't build the thing yet -- crafting from your researched blueprints arrives with the Fabricator, the next feature; for now, research is how you line up what's coming. Themes now recolor the whole interface -- panels and secondary text shift to match your chosen color, not just the accents and borders -- so each theme reads as one cohesive look instead of colored highlights on a fixed blue panel. Fuel readouts are more honest: the net rate now counts what the refinery is ACTUALLY producing (zero when you're out of Deuterium Ice) instead of its theoretical max, and a new fuel-runway readout estimates how long until your tank runs dry -- crediting the ice your running missions keep mining, so a self-sustaining fleet reads as such. Research projects now show a progress bar and time remaining right on the blueprint, and all research durations read as real time (~2h 15m) instead of raw ticks." },
  { version: "0.9.0", summary: "Five missions available from the start -- a free Local Deuterium Skim that gathers fuel-grade Deuterium Ice at no fuel cost, plus Local Asteroid, Lunar Mine Contract, Salvage Skirmish Wreckage, and Forage Minerals & Flora, the four resource runs each hauling back its own trio of raw materials (12 in total to feed future crafting). Salvage and Forage ask for a slightly more experienced captain before they'll launch. New Mission Control facility tracks your available missions and their completion counts; more missions will unlock here as new content arrives. Missions now burn fuel for the round trip, and fuel runs on a proper economy: the new Fuel Depot automatically refines Deuterium Ice into fuel through processing pipelines you can expand (upgrade for more pipelines, more fuel per batch, and less ice per batch) -- run the free fuel skim, refine the ice, and you stay self-sufficient. If a captain is short at launch, the shortfall is auto-bought with credits as a pricey backup -- costing a short refuel delay on that trip -- and only stops repeating if you're also out of credits. A fuel gauge in the top bar shows at a glance whether you're producing more fuel than you're burning. Each ship has its own fuel capacity (how far it can range) and engine efficiency (how little it burns). Every mission now shows its XP earned per tick and its dispatch requirements up front (captain level, cargo space, fuel), with a clear reason spelled out when you can't launch. Also: warehouse fill-tiles are smaller on desktop, and their tooltips now open on a single tap on mobile." },
  { version: "0.8.0", summary: "New Warehouse facility: your materials now have real storage, split into Raw / Refined / Component tabs (plus placeholder tabs for what's coming), each with a fill-tile gauge showing how full it is, and timed capacity upgrades that double how much you can hold. Storage now has caps -- producers automatically pause when a material is full instead of wasting it. Refining got a proper order system: queue a fixed batch (Refine N) or run it continuously, watch live status and why it paused (out of ingredients, or storage full), stop an order any time, with an optional confirmation prompt you can toggle in the System tab's Options. Offline progress now advances your facilities while you're away, capped at 2 days. Groundwork for a bigger crafting economy: the base ores are renamed to Titanium / Polysilicate / Iridium Ore, with placeholder raw, refined, and component items seeded for future recipes." },
  { version: "0.7.0", summary: "Navigation reorganized: Homeworld and Sector Space are now unified under a new Locations tab -- each place keeps its own sub-tabs -- and Facilities are grouped by owner (Homeworld, Fleet Sector, Ships). Same content, tidier layout, fewer tabs." },
  { version: "0.6.0", summary: "New Facilities tab: you can now build and upgrade a Refinery, then run refine jobs that turn common ore into refined material over time -- each upgrade unlocks another refine slot so several jobs run at once, with the later upgrades gated behind your Fleet Admiral level and Homeworld talents. Behind the scenes, all your materials moved into a single unified inventory -- existing saves migrate automatically." },
  { version: "0.5.0", summary: "Captains and your Fleet Admiral now earn XP every tick while missions run, instead of only when a mission cycle finishes -- leveling feels steady and continuous, and the Fleet Admiral now climbs much faster the more captains you have out on missions at once. Unlocking captain slots 3 and 4 now also requires reaching a Fleet Admiral level (on top of the existing talent cost), and captain slots you can actually work toward now read \"Locked\" instead of \"Coming Soon.\"" },
  { version: "0.4.0", summary: "Ships are now real, swappable hulls with distinct stats -- cargo capacity, transit speed, and extraction yield all change how a captain's missions play out. New Sector Space > Starbase area to manage your fleet, assign hulls to captains, and buy new hulls with credits. Existing saves auto-upgrade, giving every captain a starter Freighter." },
  { version: "0.3.0", summary: "Talent trees are now an explorable radial \"skill web\" you pan around, revealing new nodes as you learn. Captains pick a specialization -- Prospector, Tactician, or Explorer -- and Fleet Admiral talents are organized into 5 navigable categories. Learned nodes power up glowing links between them. Existing saves are migrated automatically." },
  { version: "0.2.0", summary: "Reworked mission loot so uncommon and rare materials can both drop in the same tick instead of one replacing the others; talent bonuses now target a specific material tier each. Added Import Save. Version numbering restarts here -- 0.2.1/0.2.2 for small fixes, 0.3.0 for the next feature." },
  { version: "0.9.0", summary: "Widened the app to use most of the screen instead of a narrow centered column; retired the diagonal-corner panel look for a flatter style; moved the app's branding into this About tab." },
  { version: "0.8.0", summary: "Reworked scrolling so only the active tab's content scrolls, not the whole page; added \"Coming Soon\" locked placeholders for future sub-tabs and captain slots." },
  { version: "0.7.0", summary: "Rebuilt navigation: a global header with Fleet Admiral level/XP and a single fleet-wide tick, a dedicated Fleet Captain's tab, and a mission-first Fleet Operations tab." },
  { version: "0.6.0", summary: "Added Captain Talents and Homeworld Talents -- two talent trees plus Fleet Admiral leveling." },
];
